
select * from usuarios;
select * from roles;

alter table usuarios add constraint fk_rol foreign key (rol) references roles(id);
alter table usuarios alter column "rol" set data type integer;
alter table usuarios alter column "id" set data type integer;
alter table usuarios alter column "id" add generated by default as identity;
alter table roles alter column "id" set data type integer;
alter table roles alter column "id" add generated by default as identity;
ALTER TABLE usuarios ALTER COLUMN amaterno DROP NOT NULL;
ALTER TABLE usuarios ADD CONSTRAINT usuarios_correo_unique UNIQUE (correo);
ALTER TABLE usuarios ADD COLUMN activo BOOLEAN DEFAULT true;


insert into roles (rol) values ('admin');
insert into roles (rol) values ('docente');
insert into roles (rol) values ('estudiante');
insert into roles (rol) values ('jefedepto');
insert into usuarios (nombre, apaterno, amaterno, correo, pass, rol) values ('admin', 'padmin', 'madmin', 'admin@admin.com', 'admin', 1);

update roles set rol = 'Admin' where id = 1;
update roles set rol = 'Docente' where id = 2;
update roles set rol = 'Estudiante' where id = 3;
update roles set rol = 'Jefe de departamento' where id = 4;

-- 1.1 Agregar columna activo (eliminación lógica)
ALTER TABLE public.usuarios
ADD COLUMN IF NOT EXISTS activo BOOLEAN NOT NULL DEFAULT true;

-- 1.2 Unicidad de correo
ALTER TABLE public.usuarios
ADD CONSTRAINT usuarios_correo_unique UNIQUE (correo);

CREATE TABLE IF NOT EXISTS public.perfiles_usuario (
  usuario_id INTEGER PRIMARY KEY,
  nombre_completo TEXT NOT NULL,
  nombres TEXT NULL,
  apellidos TEXT NULL,

  CONSTRAINT fk_perfil_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.estudiantes (
  usuario_id INTEGER PRIMARY KEY,
  matricula TEXT NOT NULL UNIQUE,

  CONSTRAINT fk_estudiante_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.docentes (
  usuario_id INTEGER PRIMARY KEY,

  CONSTRAINT fk_docente_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.jefaturas (
  id SERIAL PRIMARY KEY,
  usuario_id INTEGER NOT NULL,
  departamento_id INTEGER NOT NULL,
  periodo_id INTEGER NULL,        -- si es por periodo; si no, puede ser NULL
  activo BOOLEAN NOT NULL DEFAULT true,
  creado_en TIMESTAMP NOT NULL DEFAULT now(),

  CONSTRAINT fk_jefatura_usuario
    FOREIGN KEY (usuario_id) REFERENCES public.usuarios(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.periodos (
  id SERIAL PRIMARY KEY,
  codigo TEXT NOT NULL UNIQUE,        -- "2025-1"
  fecha_inicio DATE NULL,
  fecha_fin DATE NULL,
  activo BOOLEAN NOT NULL DEFAULT true,
  creado_en TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.departamentos (
  id SERIAL PRIMARY KEY,
  nombre TEXT NOT NULL UNIQUE,
  creado_en TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.materias (
  id SERIAL PRIMARY KEY,
  clave TEXT NOT NULL UNIQUE,         -- CLAVE MATERIA
  nombre TEXT NOT NULL,               -- NOMBRE MATERIA
  departamento_id INTEGER NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT now(),

  CONSTRAINT fk_materia_departamento
    FOREIGN KEY (departamento_id) REFERENCES public.departamentos(id)
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.grupos_oferta (
  id SERIAL PRIMARY KEY,
  periodo_id INTEGER NOT NULL,
  materia_id INTEGER NOT NULL,
  grupo TEXT NOT NULL,                   -- "A", "B", "1", etc.
  docente_usuario_id INTEGER NOT NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT now(),

  CONSTRAINT fk_oferta_periodo
    FOREIGN KEY (periodo_id) REFERENCES public.periodos(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,

  CONSTRAINT fk_oferta_materia
    FOREIGN KEY (materia_id) REFERENCES public.materias(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,

  CONSTRAINT fk_oferta_docente_usuario
    FOREIGN KEY (docente_usuario_id) REFERENCES public.usuarios(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Evita duplicar la misma oferta
CREATE UNIQUE INDEX IF NOT EXISTS ux_grupos_oferta
ON public.grupos_oferta (periodo_id, materia_id, grupo, docente_usuario_id);

CREATE TABLE IF NOT EXISTS public.inscripciones (
  id SERIAL PRIMARY KEY,
  grupo_oferta_id INTEGER NOT NULL,
  estudiante_usuario_id INTEGER NOT NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT now(),

  CONSTRAINT fk_inscripcion_oferta
    FOREIGN KEY (grupo_oferta_id) REFERENCES public.grupos_oferta(id)
    ON UPDATE CASCADE ON DELETE RESTRICT,

  CONSTRAINT fk_inscripcion_estudiante_usuario
    FOREIGN KEY (estudiante_usuario_id) REFERENCES public.usuarios(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_inscripciones
ON public.inscripciones (grupo_oferta_id, estudiante_usuario_id);


CREATE TABLE IF NOT EXISTS public.import_lotes (
  id SERIAL PRIMARY KEY,
  periodo_id INTEGER NOT NULL,
  archivo_nombre TEXT NOT NULL,
  archivo_hash TEXT NULL,
  estado TEXT NOT NULL DEFAULT 'pendiente',  -- pendiente|procesando|completado|error
  errores_count INTEGER NOT NULL DEFAULT 0,
  creado_en TIMESTAMP NOT NULL DEFAULT now(),

  CONSTRAINT fk_import_lote_periodo
    FOREIGN KEY (periodo_id) REFERENCES public.periodos(id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.import_registros (
  id SERIAL PRIMARY KEY,
  lote_id INTEGER NOT NULL,
  row_num INTEGER NOT NULL,

  departamento TEXT NULL,
  materia_nombre TEXT NULL,
  materia_clave TEXT NULL,
  grupo TEXT NULL,

  profesor_nombre TEXT NULL,
  profesor_email TEXT NULL,

  matricula TEXT NULL,
  alumno_nombre TEXT NULL,
  alumno_email TEXT NULL,

  procesado BOOLEAN NOT NULL DEFAULT false,
  error TEXT NULL,
  creado_en TIMESTAMP NOT NULL DEFAULT now(),

  CONSTRAINT fk_import_registro_lote
    FOREIGN KEY (lote_id) REFERENCES public.import_lotes(id)
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_import_registros_lote
ON public.import_registros (lote_id);

CREATE INDEX IF NOT EXISTS ix_import_registros_procesado
ON public.import_registros (lote_id, procesado);

ALTER TABLE public.jefaturas
ADD CONSTRAINT fk_jefatura_departamento
FOREIGN KEY (departamento_id) REFERENCES public.departamentos(id)
ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE public.jefaturas
ADD CONSTRAINT fk_jefatura_periodo
FOREIGN KEY (periodo_id) REFERENCES public.periodos(id)
ON UPDATE CASCADE ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS ix_usuarios_activo
ON public.usuarios (activo);

INSERT INTO public.periodos (codigo, activo)
VALUES ('2025-1', true)
ON CONFLICT (codigo) DO NOTHING;

ALTER TABLE public.usuarios
ADD COLUMN IF NOT EXISTS must_change_pass boolean NOT NULL DEFAULT false;

CREATE INDEX IF NOT EXISTS ix_usuarios_must_change_pass
ON public.usuarios (must_change_pass);

CREATE UNIQUE INDEX IF NOT EXISTS ux_import_lotes_periodo_hash
ON public.import_lotes (periodo_id, archivo_hash);