
select * from usuarios;
select * from roles;

alter table usuarios add constraint fk_rol foreign key (rol) references roles(id);
alter table usuarios alter column "rol" set data type integer;
alter table usuarios alter column "id" set data type integer;
alter table usuarios alter column "id" add generated by default as identity;
alter table roles alter column "id" set data type integer;
alter table roles alter column "id" add generated by default as identity;
insert into roles (rol) values ('admin');
insert into roles (rol) values ('docente');
insert into roles (rol) values ('estudiante');
insert into roles (rol) values ('jefedepto');
insert into usuarios (nombre, apaterno, amaterno, correo, pass, rol) values ('admin', 'padmin', 'madmin', 'admin@admin.com', 'admin', 1);

update roles set rol = 'Admin' where id = 1;
update roles set rol = 'Docente' where id = 2;
update roles set rol = 'Estudiante' where id = 3;
update roles set rol = 'Jefe de departamento' where id = 4;